import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
// import QuickLinks from "./QuickLinks";
import dynamic from "next/dynamic";
import Header from "./Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}
      >
        {/* Arka plan gradienti tüm sayfaya */}
        <div className="fixed inset-0 -z-10 bg-gradient-to-br from-primary/10 via-white to-primary/5" />
        <Header />
        <main className="w-full px-4 sm:px-8 py-8 min-h-[80vh]">
          {children}
        </main>
      </body>
    </html>
  );
}
